# Generated by Django 3.0.2 on 2020-01-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200113_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
