# Generated by Django 3.0.2 on 2020-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200115_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='grandtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
