# Generated by Django 3.0.2 on 2020-01-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200121_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='grandtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
