# Generated by Django 3.0.2 on 2020-01-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200122_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='grandtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
