# Generated by Django 3.0.2 on 2020-01-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200122_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='grandtotal',
        ),
    ]
