# Generated by Django 3.0.2 on 2020-01-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grandtotal', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('orderitems', models.ManyToManyField(to='user.Cart')),
            ],
        ),
    ]
