# Generated by Django 3.0.2 on 2020-01-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200128_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_phone',
        ),
    ]
