# Generated by Django 3.0.2 on 2020-01-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200128_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderitems',
            field=models.ManyToManyField(blank=True, null=True, to='user.Product'),
        ),
    ]
